all: fifo socket queue

fifo:
	gcc fifo_p1.c -o fifo_p1
	gcc fifo_p2.c -o fifo_p2

socket:
	gcc socket_p1.c -o socket_p1
	gcc socket_p2.c -o socket_p2

queue:
	gcc queue_p1.c -o queue_p1
	gcc queue_p2.c -o queue_p2